[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[scheduled.functions]]
  name = "reminder"
  cron = "0 * * * *"
